c/template/cappuccino/karaoke_720.css, c/template/digital/karaoke_720.css, c/template/emerald/karaoke_720.css, c/template/ocean_blue/karaoke_720.css
fixed css for all themes (karaoke_720p)   except the default theme (issue #4979)
=> fixed css for all themes (karaoke_720p)   except the default theme (issue #4979)

server/administrator/add_video.php, server/administrator/get.php, server/administrator/get_img.php, server/config.ini, server/lib/kinopoisk.class.php, server/lib/restcommandsendevent.class.php, server/lib/restcommandstbmsg.class.php, server/lib/stbapi/vclubinfo.class.php, server/lib/tmdb.class.php, server/lib/vclubinfo.class.php
add autofill by themoviedb.org, switching in [vclub_info] section in the config.ini (issuie #1497)
=> add autofill by themoviedb.org, switching in [vclub_info] section in the config.ini (issuie #1497)

server/administrator/add_video.php, server/administrator/get_img.php, server/config.ini
=> fix for issuie #1497

c/player.js, server/lib/vod.class.php
The problem with advertising in video clubs (issue #5024)
=> The problem with advertising in video clubs (issue #5024)

storage/lib/vclub.class.php
Determination of the series on the pattern sXXeXX (issue # 4578).
=> Determination of the series on the pattern sXXeXX (issue # 4578).

c/player.js, c/vclub.js, server/administrator/add_video.php, server/lib/vod.class.php
Series with custom url and sXXeXX title (issue #5084)
=> Series with custom url and sXXeXX title (issue #5084)

c/layer.modal_form.js, c/vclub.js
Search in video club (issue #5229)
=> Search in video club (issue #5229)

c/radio.js, db/delta/94-add_fav_radio_table.sql, server/lang/stb.php, server/lib/radio.class.php, server/lib/stbapi/radio.class.php
Modifications section Radio - full functionality (issue #4981)
=> Modifications section Radio - full functionality (issue #4981)

c/keydown.observer.js
mouse right click event for airmouse (issue #5249)
=> mouse right click event for airmouse (issue #5249)

external/youtube/index.html, external/youtube/js/base-funcs.js, external/youtube/js/common.js, external/youtube/js/key-processing.js, external/youtube/js/objs.js, external/youtube/js/variables.js, external/youtube/js/youtube-dl.js, external/youtube/package.json
Update the application youtube (issue #5256)
=> Update the application youtube (issue #5256)

c/media_browser.js, c/settings.common.js, c/settings.localization.js, c/settings.network_status.js, c/settings.parent.js, c/settings.playback.js, c/settings.update.js, c/time_shift.js, c/usbdisk.js
Remove check the firmware version (issue # 5275)
=> Remove check the firmware version (issue # 5275)

c/radio.js, server/lib/radio.class.php
Do not open the radio section (issue # 5285)
=> Do not open the radio section (issue # 5285)

admin/resources/views/Users_users_consoles_groups.twig
fix create new group in "User groups" (issue #4623)
=> fix create new group in "User groups" (issue #4623)

admin/resources/views/Settings_common.twig
fix firmware modal window header (issue #4623)
=> fix firmware modal window header (issue #4623)

server/adm/css/style.css
fix DataTable preloader (issue #4623)
=> fix DataTable preloader (issue #4623)

c/radio.js, c/template/cappuccino/layer.sidebar.css, c/template/cappuccino/layer.sidebar_480.css, c/template/cappuccino/layer.sidebar_720.css, c/template/digital/layer.sidebar.css, c/template/digital/layer.sidebar_480.css, c/template/digital/layer.sidebar_720.css, c/template/emerald/layer.sidebar.css, c/template/emerald/layer.sidebar_480.css, c/template/emerald/layer.sidebar_720.css, c/template/ocean_blue/layer.sidebar.css, c/template/ocean_blue/layer.sidebar_480.css, c/template/ocean_blue/layer.sidebar_720.css, server/administrator/services_packages.php, server/config.ini, server/lib/itv.class.php
The order of channels in the package (issue #4253)
=>  The order of channels in the package (issue #4253)

c/radio.js, c/widget.radio.js
The problem with the display and playback of boundary elements of the list of radio stations (issue #5334)
=> The problem with the display and playback of boundary elements of the list of radio stations (issue #5334)

server/config.ini, server/lib/itv.class.php
Nginx secure link hash rule in the config.ini (issue #5332)
=> Nginx secure link hash rule in the config.ini (issue #5332)

c/xpcom.common.js, server/config.ini, server/lib/stb.class.php
Disable certificate validation if Initialization player (issue #5354)
=> Disable certificate validation if Initialization player (issue #5354)

admin/resources/views/Infoportal_phone_book.twig, admin/src/Controller/InfoportalController.php, admin/src/Model/UsersModel.php, server/adm/js/devoops.js
Fixes in functionality of admin panel Stalker (issue #5355)
=> Fixes in functionality of admin panel Stalker (issue #5355)

deploy/build.xml
The problem with localhost, and mysql (issue #5341)
=> The problem with localhost, and mysql (issue #5341)

c/player.js
Restoring playback when the TV channel - fix 2 (issue #5339)
=> Restoring playback when the TV channel - fix 2 (issue #5339)

c/player.js
Add the missing encoding for subtitles  (issue #5369)
=> Add the missing encoding for subtitles  (issue #5369)

admin/src/Controller/BroadcastServersController.php, admin/src/Controller/StatisticsController.php, admin/src/Controller/UsersController.php, admin/src/Model/UsersModel.php
The errors in the Apache-log from  new admin-panel (issue #5380)
=> The errors in the Apache-log from  new admin-panel (issue #5380)

admin/src/Controller/VideoClubController.php, c/player.js
No playback video - fix (issue #5402)
=> No playback video - fix (issue #5402)

admin/src/Model/TvChannelsModel.php
Non-working TV channel (issue #5404)
=> Non-working TV channel (issue #5404)

c/service_management.js
Password input window in the personal account (issue #1448)
=> Password input window in the personal account (issue #1448)

admin/src/Controller/StatisticsController.php, admin/src/Controller/UsersController.php
Error when editing a user in the new interface (issue #5429)
=> Error when editing a user in the new interface (issue #5429)

admin/src/Controller/BaseStalkerController.php, admin/src/Controller/TvChannelsController.php
Error in section IPTV channels -> Genres (issue #5430)
=> Error in section IPTV channels -> Genres (issue #5430)

c/player.js, c/radio.js, c/widget.radio.js, server/lib/radio.class.php
Widget radio - an error in the console (issue #5438)
=> Widget radio - an error in the console (issue #5438)

admin/resources/views/Storages_storages_video_search.twig, admin/src/Controller/StatisticsController.php, admin/src/Controller/StoragesController.php, admin/src/Model/AdminsModel.php, admin/src/Model/AudioClubModel.php, admin/src/Model/BaseStalkerModel.php, admin/src/Model/BroadcastServersModel.php, admin/src/Model/EventsModel.php, admin/src/Model/InfoportalModel.php, admin/src/Model/KaraokeModel.php, admin/src/Model/RadioModel.php, admin/src/Model/SettingsModel.php, admin/src/Model/StatisticsModel.php, admin/src/Model/StoragesModel.php, admin/src/Model/TariffsModel.php, admin/src/Model/TasksModel.php, admin/src/Model/TvChannelsModel.php, admin/src/Model/UsersModel.php, admin/src/Model/VideoClubModel.php, c/player.js
Playing channel after turning on the TV (issue #5432)
=> Playing channel after turning on the TV (issue #5432)

admin/src/Controller/UsersController.php
Error of user editing  (issue #5494)
=> Error of user editing  (issue #5494)

admin/resources/views/Admins_admins_groups_permissions.twig, admin/src/Controller/AdminsController.php
Unable to expose the full rights (issue #5495)
=> Unable to expose the full rights (issue #5495) 

server/adm/css/style.css
Cropped context menu when a short table (issue #5523)
=> Cropped context menu when a short table (issue #5523)

c/radio.js
Freezing consoles by pressing MODE (issue #5538)
=> Freezing consoles by pressing MODE (issue #5538)

admin/src/Controller/UsersController.php
EOF on user  profile  (issue #5564)
=> EOF on user  profile  (issue #5564)

c/player.js
Error playing the TV channel at the exit from the main menu (issue #5597)
=> Error playing the TV channel at the exit from the main menu (issue #5597)

admin/resources/views/Admins_admins_groups_permissions.twig, admin/resources/views/TvChannels_epg.twig, admin/src/Controller/BaseStalkerController.php, db/delta/104-update_adm_grp_action_access.sql
Error opening some pages in the new admin (issue #5609)
=> Error opening some pages in the new admin (issue #5609)

admin/resources/views/Index_index.twig, admin/src/Controller/VideoClubController.php
New admin panel - error adding video (issue #5657)
=> New admin panel - error adding video (issue #5657)

admin/src/Controller/BaseStalkerController.php, admin/src/Controller/UsersController.php
Error of the opening add-user form  (issue #5661)
=> Error of the opening add-user form  (issue #5661)

admin/resources/views/Settings_common.twig, admin/src/Controller/SettingsController.php, admin/src/Controller/TariffsController.php
Error of editing of the service-package (issue #5667)
=> Error of editing of the service-package (issue #5667)

c/radio.js, c/widget.radio.js, server/lib/radio.class.php
In the radio-widget only 14 stations (issue #5653)
=> In the radio-widget only 14 stations (issue #5653)

admin/src/Controller/IndexController.php
Percentage of loading of the stream-server  (issue #5676)
=> Percentage of loading of the stream-server  (issue #5676)

admin/resources/views/VideoClub_video_list.twig, admin/src/Controller/VideoClubController.php, external/settings/g_dvb.html
DVB specify the frequency manually  (issue #5641)
=> DVB specify the frequency manually  (issue #5641)

admin/src/Model/StatisticsModel.php
In the statistics are displayed deleted tv channels  (issue #5823)
=> In the statistics are displayed deleted tv channels  (issue #5823)

admin/src/Controller/AdminsController.php, admin/src/Controller/TvChannelsController.php, admin/src/Model/TvChannelsModel.php
New admin-panel - fix by list - 1.26 (issue#5900)
=> New admin-panel - fix by list - 1.26 (issue#5900)

db/delta/109-filters.sql
=>  fix 109-filters.sql

admin/src/Controller/UsersController.php, db/delta/113-fix_filters_action.sql
=> fix for UsersList

admin/resources/views/ApplicationCatalog_application_detail.twig, admin/src/Controller/ApplicationCatalogController.php
Catalog of applications - end end adding autoupdate option (issue # 5884)
=> Catalog of applications - end end adding autoupdate option (issue # 5884)

admin/resources/views/Tariffs_add_service_package.twig, admin/resources/views/TvChannels_tv_genres.twig, admin/resources/views/VideoClub_video_categories.twig, admin/resources/views/basic_templates/footer_js.twig, admin/src/Controller/BaseStalkerController.php, server/adm/js/devoops.js
No pagination on the channels page (issue # 5920)
=> No pagination on the channels page (issue # 5920)

admin/resources/views/VideoClub_add_video.twig, server/adm/js/devoops.js
=> fix modal close

db/delta/123-update_application_tos.sql
Update application tos (issue #6074)
=> Update application tos (issue #6074) 

admin/src/Controller/UsersController.php, admin/src/Model/UsersModel.php
Title of profile of the console (issue #6077)
=> Title of profile of the console (issue #6077)

admin/src/Controller/TvChannelsController.php
Failure to open the edit channel (issue #6092)
=> Failure to open the edit channel (issue #6092)

admin/resources/views/Users_users_list.twig, admin/src/Controller/UsersController.php
Broken date of turnoff consoles (issue #6091)
=> Broken date of turnoff consoles (issue #6091)

admin/resources/views/Radio_add_radio.twig, admin/src/Controller/RadioController.php
Bugs a clean install from dev branches - Radio (issue #6116)
=> Bugs a clean install from dev branches - Radio (issue #6116)

admin/resources/views/Events_event_scheduler.twig, admin/resources/views/Users_users_filter_list.twig, admin/resources/views/basic_templates/scheduler_events_menu.twig
Bugs a clean install from dev branches - Events  (issue #6122)
=> Bugs a clean install from dev branches - Events  (issue #6122) 

admin/resources/views/TvChannels_iptv_list.twig, admin/src/Controller/IndexController.php, admin/src/Controller/TvChannelsController.php, admin/src/Controller/VideoClubController.php, server/adm/.htaccess
The problem with access to the admin-panel if portal not in /stalker_portal folder (issue #6145)
=> The problem with access to the admin-panel if portal not in /stalker_portal folder (issue #6145)

admin/src/Controller/ApplicationCatalogController.php
Refresh button on the application  (issue #6187)
=> Refresh button on the application  (issue #6187)

admin/src/Controller/TvChannelsController.php, deploy/composer.json, server/lib/filters.class.php
empty user's  profile (issue #6209)
=> empty user's  profile (issue #6209)

admin/src/Lib/Save.php
Do not add the logo image to the channel (issue #6215)
=> Do not add the logo image to the channel (issue #6215)

admin/resources/views/Admins_admins_groups.twig, admin/resources/views/TvChannels_add_channel.twig, admin/src/Controller/TvChannelsController.php, server/adm/js/devoops.js, server/adm/plugins/datatables/dataTables.bootstrap.js
Can not open editing channel (issue #6218)
=> Can not open editing channel (issue #6218)

admin/resources/views/TvChannels_iptv_list.twig, admin/src/Controller/TvChannelsController.php, server/tasks/send_user_expire_date_msg.php
Errors when sending messages about disabling (issue #6262)
=> Errors when sending messages about disabling (issue #6262)

admin/src/Model/TvChannelsModel.php
Failed to add channel (issue #6321)
=> Failed to add channel (issue #6321)

admin/resources/views/Admins_admins_groups.twig, admin/resources/views/ApplicationCatalog_application_detail.twig, admin/resources/views/ApplicationCatalog_application_list.twig, admin/resources/views/AudioClub_audio_albums.twig, admin/resources/views/BroadcastServers_broadcast_servers_list.twig, admin/resources/views/BroadcastServers_broadcast_zone_list.twig, admin/resources/views/Events_message_templates.twig, admin/resources/views/Infoportal_humor.twig, admin/resources/views/Infoportal_phone_book.twig, admin/resources/views/Karaoke_index.twig, admin/resources/views/Radio_index.twig, admin/resources/views/Settings_common.twig, admin/resources/views/Storages_storages_list.twig, admin/resources/views/Tariffs_service_packages.twig, admin/resources/views/Tariffs_tariff_plans.twig, admin/resources/views/TvChannels_iptv_list.twig, admin/resources/views/Users_users_filter_list.twig, admin/resources/views/Users_users_list.twig, admin/resources/views/VideoClub_video_list.twig, admin/src/Controller/InfoportalController.php, server/adm/plugins/datatables/dataTables.bootstrap.js, server/lib/filters.class.php, server/lib/vod.class.php
Shows only the first letter of genres (issue #6335)
=> Shows only the first letter of genres (issue #6335)

admin/resources/views/VideoClub_add_video.twig, admin/src/Controller/VideoClubController.php
When added to the film cover oversized launcher hangs (issue #6380)
=> When added to the film cover oversized launcher hangs (issue #6380)

admin/resources/views/Radio_add_radio.twig, admin/src/Controller/RadioController.php, admin/src/Controller/UsersController.php, admin/src/Model/UsersModel.php, server/lib/filters.class.php
=> (issue #6528, #6529)

admin/resources/views/TvChannels_add_channel.twig, server/adm/js/devoops.js
IPTV: the "URL channel for monitoring" is required, when the monitoring is enabled (issue # 6619)
=> (issue # 6619)

admin/src/Controller/SettingsController.php
small fix in  "Settings - Theme"
=> small fix in  "Settings - Theme"

admin/src/Controller/SettingsController.php, admin/src/Controller/UsersController.php
=>  (issue #7006)

c/index.html, server/api/load_js.php, server/config.ini
Add support MaxCDN (issue #7019)
=> Add support MaxCDN (issue #7019)

admin/resources/views/ApplicationCatalog_smart_application_detail.twig, admin/resources/views/ApplicationCatalog_smart_application_list.twig, admin/src/Controller/ApplicationCatalogController.php, db/delta/164-add_admin_permitions_data.sql
The interface for the npm-application - pre-commit 9 (issue #7602)
=> The interface for the npm-application - pre-commit 9 (issue #7602)

admin/src/Controller/ApplicationCatalogController.php
=> Applications - deleting apps

admin/resources/views/NewVideoClub_add_video.twig, admin/src/Controller/ApplicationCatalogController.php
=> (issue #7749)
